### ISSUE TITLE
import gpytorch error

### ISSUE THREAD

**Issue by chalesguo** [jrg365/gpytorch#18]
$ python 
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/gpytorch-master/gpytorch/__init__.py", line 3, in <module>
    from .lazy import LazyVariable, ToeplitzLazyVariable
  File "/home/ubuntu/gpytorch-master/gpytorch/lazy/__init__.py", line 2, in <module>
    from .toeplitz_lazy_variable import ToeplitzLazyVariable
  File "/home/ubuntu/gpytorch-master/gpytorch/lazy/toeplitz_lazy_variable.py", line 4, in <module>
    from gpytorch.utils import toeplitz
  File "/home/ubuntu/gpytorch-master/gpytorch/utils/toeplitz.py", line 2, in <module>
    import gpytorch.utils.fft as fft
  File "/home/ubuntu/gpytorch-master/gpytorch/utils/fft.py", line 1, in <module>
    from .. import libfft
  File "/home/ubuntu/gpytorch-master/gpytorch/libfft/__init__.py", line 3, in <module>
    from ._libfft import lib as _lib, ffi as _ffi
ImportError: No module named 'gpytorch.libfft._libfft'
>>>

**Comment by gpleiss** [comment]
Run `python setup.py install`
