### ISSUE TITLE
ImportError: No module named 'gpytorch.random_variables'

### ISSUE THREAD

**Issue by chalesguo** [jrg365/gpytorch#8]
>>> import gpytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gpytorch-0.1-py3.5.egg/gpytorch/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gpytorch-0.1-py3.5.egg/gpytorch/distribution.py", line 3, in <module>
ImportError: No module named 'gpytorch.random_variables'

**Comment by chalesguo** [comment]
After reinstalling, it works fine.
